# Generated by Django 4.1.4 on 2022-12-25 10:04

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', colorfield.fields.ColorField(default='000000', image_field=None, max_length=18, samples=None)),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название предмета')),
                ('vendor_name', models.CharField(default='0', max_length=20, null=True, verbose_name='Артикул')),
                ('price', models.IntegerField(verbose_name='Стоимость в рублях')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('material', models.TextField(max_length=300, verbose_name='Материал')),
                ('equipment', models.TextField(max_length=500, verbose_name='Комплектация')),
                ('peculiarities', models.TextField(max_length=500, verbose_name='Особенности')),
                ('guarantee', models.TextField(max_length=500, verbose_name='Гарантийный срок')),
                ('parameters', models.TextField(default=None, max_length=300, verbose_name='Параметры')),
                ('categories', models.ManyToManyField(related_name='categories', to='shop.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.color', verbose_name='Цвет предмета')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Цвет предмета',
                'verbose_name_plural': 'Цвета предмета',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона')),
                ('address', models.TextField(max_length=500, verbose_name='Адрес')),
                ('comment', models.TextField(max_length=500, verbose_name='Комментарии к заказу')),
                ('promo_code', models.CharField(max_length=12, verbose_name='Промокод')),
                ('pay_method', models.CharField(choices=[('IND', 'Car payment for individual'), ('ENT', 'Cashless payment for entity')], default='IND', max_length=3, verbose_name='Метод оплаты')),
                ('agreement', models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа')),
                ('complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Выполнен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество предметов в заказе')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.itemcolor', verbose_name='Предмет')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Предмет из заказа',
                'verbose_name_plural': 'Предметы из заказов',
            },
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='Изображение')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Изображение предмета',
                'verbose_name_plural': 'Изображения предметов',
            },
        ),
    ]
