# Generated by Django 4.1.4 on 2022-12-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor_name',
            field=models.CharField(default='-', max_length=20, null=True, verbose_name='Артикул'),
        ),
    ]
