# Generated by Django 4.1.4 on 2022-12-25 13:54

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_concept_item_production_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcolor',
            options={'verbose_name': 'Цвет предмета', 'verbose_name_plural': 'Цвета предметов'},
        ),
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.FileField(upload_to=shop.models.file_directory_path, verbose_name='Изображение'),
        ),
    ]
