# Generated by Django 4.1.4 on 2022-12-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_item_comment_alter_itemcolor_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageitem',
            name='image_path',
            field=models.FilePathField(blank=True, null=True, path='/media/'),
        ),
    ]
