# Generated by Django 4.1.4 on 2022-12-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_imageitem_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='image_path',
            field=models.FilePathField(blank=True, null=True, path='/media/', recursive=True),
        ),
    ]
