# Generated by Django 4.1.4 on 2022-12-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_imageitem_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageitem',
            name='image_path',
        ),
    ]
