# Generated by Django 4.1.4 on 2023-01-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_item_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название цвета'),
        ),
    ]
