# Generated by Django 4.1.4 on 2023-01-07 12:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(max_length=500, null=True, verbose_name='Комментарии к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата оформления заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('IND', 'Car payment for individual'), ('ENT', 'Cashless payment for entity')], default='IND', max_length=3, null=True, verbose_name='Метод оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promo_code',
            field=models.CharField(max_length=12, null=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='order',
            name='second_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
